title: My Blog
baseurl: ""
url: "https://amencke.github.io"

remote_theme: "mmistakes/minimal-mistakes@4.27.1"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

markdown: kramdown
kramdown:
  math_engine: mathjax
  input: GFM

mathjax: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      mathjax: true
